px = [ndur{c1} ndur{c2}]; py = [vadur{c1} vadur{c2}];
lbl = [zeros(size(ndur{c1})) ones(size(ndur{c2}))];
h = scatterhist(px,py,'Group',lbl,'Kernel','on','Bandwidth',[30 30;40 40],'legend','off',...
    'Direction','out','Color',[.6 .6 .6;0 0 .7],'marker','..','LineStyle',{'-','-',':'},...
    'LineWidth',[2,2,2],'MarkerSize',[12,12]);
xlabel('5-HT neuron ON duration (min)');ylabel('Dwelling duration (min)');
set(h(1),'xtick',0:240:1000,'ytick',0:240:1000,'xticklabel',{'0' '4' '6' '8',''},...
    'yticklabel',{'0' '4' '6' '8',''},...
    'tickdir','out','ticklength',.025*ones(1,2))